services:
  ubuntu:
    image: ubuntu:latest # Levykuva https://hub.docker.com/_/ubuntu
    command: /bin/bash # Käynnistää kontissa bash-komentotulkin
    volumes:
      - ./:/app # Liittää nykyisen hakemiston /app-hakemistoksi kontin sisällä
    working_dir: /app # Asettaa /app-hakemiston työskentelyhakemistoksi kontin sisällä

    tty: true # ohjaa kontin tulosteet komentoriville
    stdin_open: true # ohjaa syötteet komentoriviltä konttiin

# Selitys:
#
# Komento `docker compose run ubuntu` suorittaa uuden Docker-kontin käyttämällä tässä tiedostossa
# määriteltyä `ubuntu`-palvelua. Komento luo uuden kontin, käynnistää siinä määritellyn 
# `command`-komennon (/bin/bash), ja tarjoaa pääsyn interaktiiviseen komentotulkkiin, koska
# palvelu on määritelty toimimaan interaktiivisesti (`tty: true` ja `stdin_open: true` asetusten avulla).
